export default {
  name: 'siteSettings',
  title: '웹사이트 설정',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: '설정 이름',
      type: 'string',
      initialValue: '웹사이트 설정',
    },
    {
      name: 'valuesJson',
      title: '설정값 JSON (전체 자동 동기화)',
      type: 'text',
      description: '웹사이트 전체 텍스트 및 설정값이 JSON 형식으로 자동 보존됩니다.',
    },
    {
      name: 'values',
      title: '페이지 문구 및 설정값',
      type: 'object',
      fields: [
        { name: 'header_title', title: '헤더 제목', type: 'string' },
        { name: 'header_subtitle', title: '헤더 부제목', type: 'string' },
        { name: 'intro_quote', title: '인트로 인용구', type: 'string' },
        { name: 'intro_sub', title: '인트로 보조문구', type: 'string' },
        { name: 'about_slogan', title: '원장소개 슬로건', type: 'string' },
        { name: 'about_name', title: '원장 이름', type: 'string' },
        { name: 'about_career', title: '원장 경력', type: 'text' },
        { name: 'about_desc', title: '교육 철학', type: 'text' },
        { name: 'curriculum_elem_title', title: '초등부 제목', type: 'string' },
        { name: 'curriculum_elem_body', title: '초등부 설명', type: 'text' },
        { name: 'curriculum_mid_title', title: '중등부 제목', type: 'string' },
        { name: 'curriculum_mid_body', title: '중등부 설명', type: 'text' },
        { name: 'info_hours', title: '운영 시간', type: 'string' },
        { name: 'info_address', title: '주소', type: 'string' },
        { name: 'info_parking', title: '주차 안내', type: 'string' },
        { name: 'contact_desc', title: '상담 안내 문구', type: 'string' },
        { name: 'contact_kakao', title: '카카오톡 상담 링크', type: 'string' },
      ],
    },
    {
      name: 'updatedAt',
      title: '최종 수정일시',
      type: 'datetime',
    },
  ],
};
